### ISSUE TITLE
why not use drawable

### ISSUE THREAD

**Issue by JonaNorman** [florent37/MyLittleCanvas#1]

**Comment by florent37** [comment]
I use this lib to create dynamics components like sliders, or trees, with drawable it's static, try to create a tree with drawables

**Comment by JonaNorman** [comment]
I not  understand  why drawable is static , for example
```
 @Override
    protected void onDraw(Canvas canvas) {
         super.onDraw(canvas);
        progressDrawable.setColor(Color.Red);//progressDrawable extend shapedrawable
          progressDrawable.draw(canvas);
            invalidate();
    }
```

**Comment by florent37** [comment]
oh I didn't understand the question,
you mean shapedrawable don't works yes ?

**Comment by JonaNorman** [comment]
I mean why not create custom drawable to create dynamics components ？

**Comment by florent37** [comment]
I don't understand.

My lib goal is to simplify usage if canvas

Le 30 nov. 2017 08:37, "HongJun2046" <notifications@github.com> a écrit :

I mean why not create custom drawable to create dynamics components ？

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/florent37/MyLittleCanvas/issues/1#issuecomment-348106755>,
or mute the thread

**Comment by JonaNorman** [comment]
I understand your meaning, but I think so, **drawable is actually the realization of canves**.
Android provide GradientDrawable, ShapeDrawable so you can achieve some simple effects.
And, you can custom like TextDrawable, UrlDrawable, this is not better?
By the way，I **am sorry for my bad English, and this is just my understanding**. You Can Close this issuse.
